#!/bin/bash -i

###Converted from AttractEasyModel by easy2model 1.3
### Generated by ATTRACT shell script generator version 0.8

set -u -e
if [ ! -f $ATTRACTDIR/attract ]; then
  echo 'Cannot find the ATTRACT binary in $ATTRACTDIR='\"$ATTRACTDIR\"
  echo 'Please install ATTRACT following the installation instructions'
  echo 'ATTRACT is available at: http://www.attract.ph.tum.de/services/ATTRACT/attract.tgz'
  exit 1
fi
if [ ! -f $ATTRACTDIR/../version ] ||  [ `awk '{print ($1 < 0.4)}' $ATTRACTDIR/../version` -eq 1 ]; then
  echo 'Your ATTRACT version is too old to run this protocol. Please download and install the latest version of ATTRACT'
  echo 'ATTRACT is available at: http://www.attract.ph.tum.de/services/ATTRACT/attract.tgz'
  exit 1
fi
trap "kill -- -$BASHPID; attractclean" ERR EXIT
$ATTRACTDIR/shm-clean

rm -rf result.dat result.pdb result.lrmsd result.irmsd result.fnat result.interface >& /dev/null
function attractclean {
  $ATTRACTDIR/shm-clean
}

#name of the run
name=attract_2020_10_15

#docking parameters
paramsprep="$ATTRACTDIR/../attract.par partner1-ensemble/model-1r.pdb ligandr.pdb --ens 1 partner1-ensemble.list --rest air-restraints.rest --rest air-restraints.rest --ghost"
params="$ATTRACTDIR/../attract.par partner1-ensemble/model-1r.pdb ligandr.pdb --fix-receptor --ens 1 partner1-ensemble.list --rest air-restraints.rest --rest air-restraints.rest"
scoreparams="$ATTRACTDIR/../attract.par partner1-ensemble/model-1r.pdb ligandr.pdb --score --fix-receptor --ens 1 partner1-ensemble.list --rest air-restraints.rest --rest air-restraints.rest --restweight 0.01"

#grid parameters
gridparams=" --grid 1 receptorgrid.gridheader"

#parallelization parameters
parals="--np 6 --chunks 6"

#see if pypy is installed
PYPY=python2
command -v pypy >/dev/null 2>&1 && PYPY=pypy

if [ 1 -eq 1 ]; then ### move and change to disable parts of the protocol

echo '**************************************************************'
echo 'Reduce partner PDBs...'
echo '**************************************************************'
rm -rf partner1-ensemble
mkdir partner1-ensemble
$ATTRACTTOOLS/splitmodel receptor.pdb partner1-ensemble/model 2 > /dev/null
cat /dev/null > partner1-ensemble.list
cat /dev/null > partner1-ensemble-aa.list
python2 $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-1.pdb partner1-ensemble/model-1-aa.pdb --chain A --dumppatch --pdb2pqr > receptor.mapping
python2 $ATTRACTTOOLS/reduce.py partner1-ensemble/model-1-aa.pdb partner1-ensemble/model-1r.pdb --chain A > /dev/null
echo partner1-ensemble/model-1r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-1-aa.pdb >> partner1-ensemble-aa.list
python2 $ATTRACTDIR/../allatom/aareduce.py partner1-ensemble/model-2.pdb partner1-ensemble/model-2-aa.pdb --chain A --dumppatch --reference partner1-ensemble/model-1-aa.pdb --pdb2pqr > /dev/null
python2 $ATTRACTTOOLS/reduce.py partner1-ensemble/model-2-aa.pdb partner1-ensemble/model-2r.pdb --chain A > /dev/null
echo partner1-ensemble/model-2r.pdb >> partner1-ensemble.list
echo partner1-ensemble/model-2-aa.pdb >> partner1-ensemble-aa.list
python2 $ATTRACTDIR/../allatom/aareduce.py ligand.pdb ligand-aa.pdb --chain B --rna --dumppatch --nalib --heavy > ligand.mapping
python2 $ATTRACTTOOLS/reduce.py ligand-aa.pdb ligandr.pdb --chain B --rna > /dev/null

echo '**************************************************************'
echo 'Generate HADDOCK AIR restraints...'
echo '**************************************************************'
python2 $ATTRACTTOOLS/air.py haddock-active-attract_2020_10_15-partner1.reslist haddock-passive-attract_2020_10_15-partner1.reslist partner1-ensemble/model-1r.pdb receptor.mapping \
                            haddock-active-attract_2020_10_15-partner2.reslist haddock-passive-attract_2020_10_15-partner2.reslist ligandr.pdb ligand.mapping \
                            0.5 3.0 1.0 > air-restraints.rest

echo '**************************************************************'
echo 'Generate starting structures...'
echo '**************************************************************'
$PYPY $ATTRACTTOOLS/randsearch.py 2 200000 --fix-receptor > randsearch.dat
start=randsearch.dat

echo '**************************************************************'
echo 'ensemble search:'
echo ' add ensemble conformations to the starting structures'
echo '**************************************************************'

echo '**************************************************************'
echo 'random ensemble conformation in ligand 1 for each starting structure'
echo '**************************************************************'
$PYPY $ATTRACTTOOLS/ensemblize.py randsearch.dat 2 1 random  > randsearch-ens1.dat

echo '**************************************************************'
echo 'calculate receptorgrid grid'
echo '**************************************************************'
awk '{print substr($0,58,2)}' ligandr.pdb | sort -nu > receptorgrid.alphabet
$ATTRACTDIR/make-grid-omp partner1-ensemble/model-1r.pdb $ATTRACTDIR/../attract.par 10.0 12.0 receptorgrid.gridheader  --shm --alphabet receptorgrid.alphabet

echo '**************************************************************'
echo 'Docking'
echo '**************************************************************'

echo '**************************************************************'
echo '1st minimization'
echo '**************************************************************'
python2 $ATTRACTDIR/../protocols/attract.py randsearch-ens1.dat $paramsprep --vmax 50 --only-rot $parals --output stage1_$name.dat
$ATTRACTDIR/fix_receptor stage1_$name.dat 2 --ens 2 0 | $PYPY $ATTRACTTOOLS/fill.py /dev/stdin stage1_$name.dat > stage1_$name.dat-fixre

echo '**************************************************************'
echo '2nd minimization'
echo '**************************************************************'
python2 $ATTRACTDIR/../protocols/attract.py stage1_$name.dat-fixre $params $gridparams --vmax 1000 $parals --output stage2_$name.dat

echo '**************************************************************'
echo '3rd minimization'
echo '**************************************************************'
python2 $ATTRACTDIR/../protocols/attract.py stage2_$name.dat $params $gridparams --vmax 1000 --restweight 0.01 $parals --output out_$name.dat

echo '**************************************************************'
echo 'Final rescoring'
echo '**************************************************************'
python2 $ATTRACTDIR/../protocols/attract.py out_$name.dat $scoreparams --rcut 50.0 $parals --output out_$name.score

echo '**************************************************************'
echo 'Merge the scores with the structures'
echo '**************************************************************'
$PYPY $ATTRACTTOOLS/fill-energies.py out_$name.dat out_$name.score > out_$name-scored.dat

echo '**************************************************************'
echo 'Sort structures'
echo '**************************************************************'
$PYPY $ATTRACTTOOLS/sort.py out_$name-scored.dat > out_$name-sorted.dat

echo '**************************************************************'
echo 'Fix all structures into the receptor's coordinate frame
echo '**************************************************************'
$ATTRACTDIR/fix_receptor out_$name-sorted.dat 2 --ens 2 0 | $PYPY $ATTRACTTOOLS/fill.py /dev/stdin out_$name-sorted.dat > out_$name-sorted.dat-fixre

echo '**************************************************************'
echo 'Remove redundant structures'
echo '**************************************************************'
$ATTRACTDIR/deredundant out_$name-sorted.dat-fixre 2 --ens 2 0 | $PYPY $ATTRACTTOOLS/fill-deredundant.py /dev/stdin out_$name-sorted.dat-fixre > out_$name-sorted-dr.dat

echo '**************************************************************'
echo 'Soft-link the final results'
echo '**************************************************************'
ln -s out_$name-sorted-dr.dat result.dat

echo '**************************************************************'
echo 'collect top 50 structures:'
echo '**************************************************************'
$ATTRACTTOOLS/top out_$name-sorted-dr.dat 50 > out_$name-top50.dat
$ATTRACTDIR/collect out_$name-top50.dat partner1-ensemble/model-1-aa.pdb ligand-aa.pdb --ens 1 partner1-ensemble-aa.list > out_$name-top50.pdb
ln -s out_$name-top50.pdb result.pdb

attractclean

fi ### move to disable parts of the protocol
